services:
  rarbg-view:
    container_name: server
    build:
      dockerfile: Dockerfile
    command: ./rarbg-view
    ports:
    - 8000:8000
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./db:/app/db
